#!/bin/bash

read -p "Input Date: " DATE
read -p "Input Time: " TIME
read -p "Input Message: " MSG
read -p "How many days' notification: " NOTIF

if [ -n "$NOTIF" ]; then  
if date -j -f "%Y/%m/%d" +%Y/%m/%d $DATE > /dev/null 2>&1 && date -j -f "%H:%M" +%H:%M $TIME > /dev/null 2>&1 && [ -n "$TIME" ] && [ -n "$MSG" ]
	then echo "REM $DATE +$NOTIF AT $TIME  MSG $MSG" >> ~/.reminders
elif  [ -z "$TIME" ] && [ -n "$MSG" ] && date -j -f "%Y/%m/%d" +%Y/%m/%d $DATE > /dev/null 2>&1
	then echo "REM $DATE +$NOTIF MSG $MSG" >> ~/.reminders
	remind -c+4 -w130 $HOME/.reminders > ~/tmp/remind_calendar 
	cat ~/tmp/remind_calendar; task
else
	echo "This is not the date format, or not time format, or message is empty!"
fi
elif [ -z "$NOTIF" ]; then 
if date -j -f "%Y/%m/%d" +%Y/%m/%d $DATE > /dev/null 2>&1 && date -j -f "%H:%M" +%H:%M $TIME > /dev/null 2>&1 && [ -n "$TIME" ] && [ -n "$MSG" ]
          then echo "REM $DATE  AT $TIME  MSG $MSG" >> ~/.reminders
  elif  [ -z "$TIME" ] && [ -n "$MSG" ] && date -j -f "%Y/%m/%d" +%Y/%m/%d $DATE > /dev/null 2>&1
          then echo "REM $DATE  MSG $MSG" >> ~/.reminders
          remind -c+4 -w130 $HOME/.reminders > ~/tmp/remind_calendar; 
	  cat ~/tmp/remind_calendar; task
  else    
          echo "This is not the date format, or not time format, or message is empty!"
  fi
fi
