#!/bin/bash
while IFS="" read -r line || [ -n "$line" ]
	do 
		date -j -f "%Y%m%d" +%Y/%m/%d $line >> $HOME/tmp/Anew 2>/dev/null
		date -j -f "%Y%m%d" +%Y/%m/%d%t%A $line >> $HOME/tmp/Anew2 2>/dev/null
	done < $HOME/tmp/A
