#!/bin/bash

touch ~/.remindtest 
read -p "Input key words: " KEYWORDS
cp -fr ~/.reminders ~/.reminders.bak

function yes_or_no {
    while true; do
        read -p "$* [y/n]: " yn
        case $yn in
            [Yy]*) return 0  ;;  
            [Nn]*) echo "Aborted" ; return  1 ;;
  	    * ) echo "Please answer Yes or No. " ;;
        esac
    done
}

grep -q -i "$KEYWORDS" ~/.reminders

if [[ $? -ne 0 ]] || [ -z "$KEYWORDS" ] 
then
	echo "No match!"
else
	cat -n ~/.reminders | grep -i "$KEYWORDS"
	read -p "Which entry do you want to remove (enter the corresponding number): " LINENUMBER
	sed "${LINENUMBER}d" ~/.reminders > ~/.remindtest | remind -w140 -c+2 ~/.remindtest
        echo "Does this look okay to you? (WARNING: This action will not be recoverable!) [y/n]: "
	yes_or_no && sed -i '' "${LINENUMBER}d" ~/.reminders;
fi
rm ~/.remindtest
