#!/bin/bash
# NOTE: GET TOKEN FROM THE AQI WEBSITE
touch $HOME/tmp/airquality
AQPATH=$HOME/tmp
TOKEN=
read -p "Which place? Country/Region or Region " PLACE
curl "https://api.waqi.info/feed/$PLACE/?token=$TOKEN" > $HOME/tmp/airquality
rm $AQPATH/values
touch $AQPATH/values
printf "\n" >> $AQPATH/values
STATUS=$(jq '.status' $AQPATH/airquality)
if [ $STATUS == '"error"' ]
then echo "Not found!"; exit 1;
else
jq '.data.attributions[0].name' $AQPATH/airquality >> $AQPATH/values
jq '.data.city.name' $AQPATH/airquality >> $AQPATH/values
jq '.data.city.url' $AQPATH/airquality >> $AQPATH/values
printf "\n" >> $AQPATH/values
jq '.data|.iaqi|.co|.v' $AQPATH/airquality >> $AQPATH/values
jq '.data|.iaqi|.dew|.v' $AQPATH/airquality >> $AQPATH/values
jq '.data|.iaqi|.h|.v' $AQPATH/airquality >> $AQPATH/values
jq '.data|.iaqi|.o3|.v' $AQPATH/airquality >> $AQPATH/values
jq '.data|.iaqi|.p|.v' $AQPATH/airquality >> $AQPATH/values
jq '.data|.iaqi|.pm10|.v' $AQPATH/airquality >> $AQPATH/values
jq '.data|.iaqi|.pm25|.v' $AQPATH/airquality >> $AQPATH/values
jq '.data|.iaqi|.so2|.v' $AQPATH/airquality >> $AQPATH/values
jq '.data|.iaqi|.t|.v' $AQPATH/airquality >> $AQPATH/values
jq '.data|.iaqi|.w|.v' $AQPATH/airquality >> $AQPATH/values
printf "\n" >> $AQPATH/values
fi
sed -i '' 's/"//g' $AQPATH/values
paste $HOME/opt/personal/airquality/Pollutants $AQPATH/values | pr -t -e24 > $AQPATH/AQI
PM25=$(jq '.data|.iaqi|.pm25|.v' $AQPATH/airquality)
if (( $PM25>0 )) && (( $PM25 < 50 )) || [ $PM25 == "50" ] 
	then sed -i '' "/^PM2.5/s/$/\t\tGood/g" $AQPATH/AQI
	cat $AQPATH/AQI $HOME/opt/personal/airquality/A
elif (( $PM25 > 50 )) && (( $PM25 < 100 )) || [ $PM25 == "100" ] 
	then sed -i '' "/^PM2.5/s/$/\t\tModerate/g" $AQPATH/AQI
	cat $AQPATH/AQI $HOME/opt/personal/airquality/B
elif (( $PM25 > 100 )) && (( $PM25 < 150 )) || [ $PM25 == "150" ]
	then sed -i '' "/^PM2.5/s/$/\t\tUnhealthy for sensitive groups/g" $AQPATH/AQI
	cat $AQPATH/AQI $HOME/opt/personal/airquality/C
elif (( $PM25 > 150 ))  && (( $PM25 < 200 ))  || [ $PM25 == "200" ]
	then sed -i '' "/^PM2.5/s/$/\t\tUnhealthy/g" $AQPATH/AQI
	cat $AQPATH/AQI $HOME/opt/personal/airquality/D
elif (( $PM25 > 200 )) && (( $PM25 < 300 )) || [ $PM25 == "300" ]
	then sed -i '' "/^PM2.5/s/$/\t\tVery Unhealthy/g" $AQPATH/AQI
	cat $AQPATH/AQI $HOME/opt/personal/airquality/E
elif (( $PM25 > 300 )) 
	then sed -i '' "/^PM2.5/s/$/\t\tHazardous/g" $AQPATH/AQI
	cat $AQPATH/AQI $HOME/opt/personal/airquality/F
else
	cat $AQPATH/AQI
fi
