#!/bin/bash

touch ~/.remindtest 
read -p "Input key words: " KEYWORDS

grep -q -i "$KEYWORDS" ~/.reminder
if [[ $? -ne 0 ]] 
then
	echo "No match!"
else
	cat -n ~/.reminder | grep -i "$KEYWORDS"
	read -p "Which entry do you want to remove (enter the corresponding number): " LINENUMBER
	sed "${LINENUMBER}d" ~/.reminder > ~/.remindtest | remind -c+3 ~/.remindtest
	echo "Does this look okay to you? (WARNING: This action will not be recoverable!)"
	select yn in "Yes" "No"; do
		case $yn in 
			Yes ) sed -i '' "${LINENUMBER}d" ~/.reminder; break;;
			No ) exit;;
		esac
	done
fi
rm ~/.remindtest
